// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CYD_SD_BREAKOUT_DEMO

#ifndef _CYD_SD_BREAKOUT_DEMO_UI_H
#define _CYD_SD_BREAKOUT_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenSDbreakoutDemo
void ui_ScreenSDbreakoutDemo_screen_init(void);
extern lv_obj_t * ui_ScreenSDbreakoutDemo;
void ui_event_SwitchGPIO18(lv_event_t * e);
extern lv_obj_t * ui_SwitchGPIO18;
extern lv_obj_t * ui_LabelGPIO18;
void ui_event_SwitchGPIO19(lv_event_t * e);
extern lv_obj_t * ui_SwitchGPIO19;
extern lv_obj_t * ui_LabelGPIO19;
void ui_event_SwitchGPIO23(lv_event_t * e);
extern lv_obj_t * ui_SwitchGPIO23;
extern lv_obj_t * ui_LabelGPIO23;
void ui_event_SwitchGPIO5(lv_event_t * e);
extern lv_obj_t * ui_SwitchGPIO5;
extern lv_obj_t * ui_LabelGPIO5;
void ui_event_ButtonViewPinout(lv_event_t * e);
extern lv_obj_t * ui_ButtonViewPinout;
void ui_event_LabelViewPinout(lv_event_t * e);
extern lv_obj_t * ui_LabelViewPinout;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_ScreenPinout
void ui_ScreenPinout_screen_init(void);
extern lv_obj_t * ui_ScreenPinout;
extern lv_obj_t * ui_ImagePinout;
void ui_event_ButtonReturn(lv_event_t * e);
extern lv_obj_t * ui_ButtonReturn;
extern lv_obj_t * ui_LabelReturn;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_micro_sd_sniffer_2_320_x_190_png);    // assets\Micro SD Sniffer 2 320 x 190.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
