// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CYD_SD_BREAKOUT_DEMO

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ClearLEDState(lv_event_t * e);
void FunctionToggleGPIO18(lv_event_t * e);
void FunctionToggleGPIO19(lv_event_t * e);
void FunctionToggleGPIO23(lv_event_t * e);
void FunctionToggleGPIO5(lv_event_t * e);
void ReturnClickedRestoreStates(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
