// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CYD_SD_BREAKOUT_DEMO

#include "../ui.h"

void ui_comp_Screen_1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Screen1_create_hook(lv_obj_t * comp)
{
}
