// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: CYD_SD_BREAKOUT_DEMO

#include "../ui.h"

void ui_ScreenSDbreakoutDemo_screen_init(void)
{
    ui_ScreenSDbreakoutDemo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSDbreakoutDemo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSDbreakoutDemo, lv_color_hex(0x52BDBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSDbreakoutDemo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchGPIO18 = lv_switch_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_SwitchGPIO18, 50);
    lv_obj_set_height(ui_SwitchGPIO18, 25);
    lv_obj_set_x(ui_SwitchGPIO18, -80);
    lv_obj_set_y(ui_SwitchGPIO18, -70);
    lv_obj_set_align(ui_SwitchGPIO18, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchGPIO18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO18, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchGPIO18, lv_color_hex(0xE6F706), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO18, 128, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelGPIO18 = lv_label_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_LabelGPIO18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPIO18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPIO18, -80);
    lv_obj_set_y(ui_LabelGPIO18, -45);
    lv_obj_set_align(ui_LabelGPIO18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPIO18, "GPIO-18");

    ui_SwitchGPIO19 = lv_switch_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_SwitchGPIO19, 50);
    lv_obj_set_height(ui_SwitchGPIO19, 25);
    lv_obj_set_x(ui_SwitchGPIO19, 80);
    lv_obj_set_y(ui_SwitchGPIO19, -70);
    lv_obj_set_align(ui_SwitchGPIO19, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchGPIO19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO19, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchGPIO19, lv_color_hex(0x1913EB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO19, 128, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelGPIO19 = lv_label_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_LabelGPIO19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPIO19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPIO19, 80);
    lv_obj_set_y(ui_LabelGPIO19, -45);
    lv_obj_set_align(ui_LabelGPIO19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPIO19, "GPIO-19");

    ui_SwitchGPIO23 = lv_switch_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_SwitchGPIO23, 50);
    lv_obj_set_height(ui_SwitchGPIO23, 25);
    lv_obj_set_x(ui_SwitchGPIO23, 80);
    lv_obj_set_y(ui_SwitchGPIO23, 30);
    lv_obj_set_align(ui_SwitchGPIO23, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchGPIO23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO23, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchGPIO23, lv_color_hex(0x0AF337), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO23, 128, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelGPIO23 = lv_label_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_LabelGPIO23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPIO23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPIO23, 80);
    lv_obj_set_y(ui_LabelGPIO23, 55);
    lv_obj_set_align(ui_LabelGPIO23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPIO23, "GPIO-23");

    ui_SwitchGPIO5 = lv_switch_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_SwitchGPIO5, 50);
    lv_obj_set_height(ui_SwitchGPIO5, 25);
    lv_obj_set_x(ui_SwitchGPIO5, -80);
    lv_obj_set_y(ui_SwitchGPIO5, 30);
    lv_obj_set_align(ui_SwitchGPIO5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchGPIO5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO5, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SwitchGPIO5, lv_color_hex(0xEB0404), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchGPIO5, 128, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelGPIO5 = lv_label_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_LabelGPIO5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGPIO5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGPIO5, -80);
    lv_obj_set_y(ui_LabelGPIO5, 55);
    lv_obj_set_align(ui_LabelGPIO5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGPIO5, "GPIO-5");

    ui_ButtonViewPinout = lv_btn_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_ButtonViewPinout, 100);
    lv_obj_set_height(ui_ButtonViewPinout, 50);
    lv_obj_set_x(ui_ButtonViewPinout, 0);
    lv_obj_set_y(ui_ButtonViewPinout, 87);
    lv_obj_set_align(ui_ButtonViewPinout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonViewPinout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonViewPinout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelViewPinout = lv_label_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_LabelViewPinout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelViewPinout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelViewPinout, 0);
    lv_obj_set_y(ui_LabelViewPinout, 87);
    lv_obj_set_align(ui_LabelViewPinout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelViewPinout, "View\nPinout");
    lv_obj_set_style_text_color(ui_LabelViewPinout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelViewPinout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelViewPinout, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ScreenSDbreakoutDemo);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -103);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "CYD SD BREAKOUT CARD DEMO");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SwitchGPIO18, ui_event_SwitchGPIO18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchGPIO19, ui_event_SwitchGPIO19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchGPIO23, ui_event_SwitchGPIO23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchGPIO5, ui_event_SwitchGPIO5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonViewPinout, ui_event_ButtonViewPinout, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelViewPinout, ui_event_LabelViewPinout, LV_EVENT_ALL, NULL);

}
